// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

type GetInfoResponse struct {
	FeeReport            *FeeReport `protobuf:"bytes,1,opt,name=fee_report,json=feeReport,proto3" json:"fee_report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetFeeReport() *FeeReport {
	if m != nil {
		return m.FeeReport
	}
	return nil
}

type ListFilesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFilesRequest) Reset()         { *m = ListFilesRequest{} }
func (m *ListFilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFilesRequest) ProtoMessage()    {}
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *ListFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesRequest.Unmarshal(m, b)
}
func (m *ListFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesRequest.Marshal(b, m, deterministic)
}
func (m *ListFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesRequest.Merge(m, src)
}
func (m *ListFilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFilesRequest.Size(m)
}
func (m *ListFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesRequest proto.InternalMessageInfo

type ListFilesResponse struct {
	Files                []*FileSlot `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListFilesResponse) Reset()         { *m = ListFilesResponse{} }
func (m *ListFilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFilesResponse) ProtoMessage()    {}
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *ListFilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFilesResponse.Unmarshal(m, b)
}
func (m *ListFilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFilesResponse.Marshal(b, m, deterministic)
}
func (m *ListFilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFilesResponse.Merge(m, src)
}
func (m *ListFilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListFilesResponse.Size(m)
}
func (m *ListFilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListFilesResponse proto.InternalMessageInfo

func (m *ListFilesResponse) GetFiles() []*FileSlot {
	if m != nil {
		return m.Files
	}
	return nil
}

type UploadFileRequest struct {
	// Types that are valid to be assigned to Event:
	//	*UploadFileRequest_Slot
	//	*UploadFileRequest_Chunk
	//	*UploadFileRequest_Finished
	Event                isUploadFileRequest_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UploadFileRequest) Reset()         { *m = UploadFileRequest{} }
func (m *UploadFileRequest) String() string { return proto.CompactTextString(m) }
func (*UploadFileRequest) ProtoMessage()    {}
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *UploadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileRequest.Unmarshal(m, b)
}
func (m *UploadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileRequest.Marshal(b, m, deterministic)
}
func (m *UploadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileRequest.Merge(m, src)
}
func (m *UploadFileRequest) XXX_Size() int {
	return xxx_messageInfo_UploadFileRequest.Size(m)
}
func (m *UploadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileRequest proto.InternalMessageInfo

type isUploadFileRequest_Event interface {
	isUploadFileRequest_Event()
}

type UploadFileRequest_Slot struct {
	Slot *NewFileSlot `protobuf:"bytes,1,opt,name=slot,proto3,oneof"`
}

type UploadFileRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type UploadFileRequest_Finished struct {
	Finished *Empty `protobuf:"bytes,3,opt,name=finished,proto3,oneof"`
}

func (*UploadFileRequest_Slot) isUploadFileRequest_Event() {}

func (*UploadFileRequest_Chunk) isUploadFileRequest_Event() {}

func (*UploadFileRequest_Finished) isUploadFileRequest_Event() {}

func (m *UploadFileRequest) GetEvent() isUploadFileRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *UploadFileRequest) GetSlot() *NewFileSlot {
	if x, ok := m.GetEvent().(*UploadFileRequest_Slot); ok {
		return x.Slot
	}
	return nil
}

func (m *UploadFileRequest) GetChunk() *FileChunk {
	if x, ok := m.GetEvent().(*UploadFileRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *UploadFileRequest) GetFinished() *Empty {
	if x, ok := m.GetEvent().(*UploadFileRequest_Finished); ok {
		return x.Finished
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UploadFileRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UploadFileRequest_Slot)(nil),
		(*UploadFileRequest_Chunk)(nil),
		(*UploadFileRequest_Finished)(nil),
	}
}

type UploadFileResponse struct {
	// Types that are valid to be assigned to Event:
	//	*UploadFileResponse_Invoice
	//	*UploadFileResponse_FinishedFile
	Event                isUploadFileResponse_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *UploadFileResponse) Reset()         { *m = UploadFileResponse{} }
func (m *UploadFileResponse) String() string { return proto.CompactTextString(m) }
func (*UploadFileResponse) ProtoMessage()    {}
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *UploadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileResponse.Unmarshal(m, b)
}
func (m *UploadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileResponse.Marshal(b, m, deterministic)
}
func (m *UploadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileResponse.Merge(m, src)
}
func (m *UploadFileResponse) XXX_Size() int {
	return xxx_messageInfo_UploadFileResponse.Size(m)
}
func (m *UploadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileResponse proto.InternalMessageInfo

type isUploadFileResponse_Event interface {
	isUploadFileResponse_Event()
}

type UploadFileResponse_Invoice struct {
	Invoice *InvoiceResponse `protobuf:"bytes,1,opt,name=invoice,proto3,oneof"`
}

type UploadFileResponse_FinishedFile struct {
	FinishedFile *FileSlot `protobuf:"bytes,2,opt,name=finished_file,json=finishedFile,proto3,oneof"`
}

func (*UploadFileResponse_Invoice) isUploadFileResponse_Event() {}

func (*UploadFileResponse_FinishedFile) isUploadFileResponse_Event() {}

func (m *UploadFileResponse) GetEvent() isUploadFileResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *UploadFileResponse) GetInvoice() *InvoiceResponse {
	if x, ok := m.GetEvent().(*UploadFileResponse_Invoice); ok {
		return x.Invoice
	}
	return nil
}

func (m *UploadFileResponse) GetFinishedFile() *FileSlot {
	if x, ok := m.GetEvent().(*UploadFileResponse_FinishedFile); ok {
		return x.FinishedFile
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UploadFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UploadFileResponse_Invoice)(nil),
		(*UploadFileResponse_FinishedFile)(nil),
	}
}

type DownloadFileRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadFileRequest) Reset()         { *m = DownloadFileRequest{} }
func (m *DownloadFileRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadFileRequest) ProtoMessage()    {}
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *DownloadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileRequest.Unmarshal(m, b)
}
func (m *DownloadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileRequest.Marshal(b, m, deterministic)
}
func (m *DownloadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileRequest.Merge(m, src)
}
func (m *DownloadFileRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadFileRequest.Size(m)
}
func (m *DownloadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileRequest proto.InternalMessageInfo

func (m *DownloadFileRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type DownloadFileResponse struct {
	// Types that are valid to be assigned to Event:
	//	*DownloadFileResponse_Invoice
	//	*DownloadFileResponse_Chunk
	//	*DownloadFileResponse_Finished
	Event                isDownloadFileResponse_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DownloadFileResponse) Reset()         { *m = DownloadFileResponse{} }
func (m *DownloadFileResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadFileResponse) ProtoMessage()    {}
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *DownloadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileResponse.Unmarshal(m, b)
}
func (m *DownloadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileResponse.Marshal(b, m, deterministic)
}
func (m *DownloadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileResponse.Merge(m, src)
}
func (m *DownloadFileResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadFileResponse.Size(m)
}
func (m *DownloadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileResponse proto.InternalMessageInfo

type isDownloadFileResponse_Event interface {
	isDownloadFileResponse_Event()
}

type DownloadFileResponse_Invoice struct {
	Invoice *InvoiceResponse `protobuf:"bytes,1,opt,name=invoice,proto3,oneof"`
}

type DownloadFileResponse_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type DownloadFileResponse_Finished struct {
	Finished *Empty `protobuf:"bytes,3,opt,name=finished,proto3,oneof"`
}

func (*DownloadFileResponse_Invoice) isDownloadFileResponse_Event() {}

func (*DownloadFileResponse_Chunk) isDownloadFileResponse_Event() {}

func (*DownloadFileResponse_Finished) isDownloadFileResponse_Event() {}

func (m *DownloadFileResponse) GetEvent() isDownloadFileResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *DownloadFileResponse) GetInvoice() *InvoiceResponse {
	if x, ok := m.GetEvent().(*DownloadFileResponse_Invoice); ok {
		return x.Invoice
	}
	return nil
}

func (m *DownloadFileResponse) GetChunk() *FileChunk {
	if x, ok := m.GetEvent().(*DownloadFileResponse_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *DownloadFileResponse) GetFinished() *Empty {
	if x, ok := m.GetEvent().(*DownloadFileResponse_Finished); ok {
		return x.Finished
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DownloadFileResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DownloadFileResponse_Invoice)(nil),
		(*DownloadFileResponse_Chunk)(nil),
		(*DownloadFileResponse_Finished)(nil),
	}
}

type FeeReport struct {
	MsatBaseCost         int64    `protobuf:"varint,1,opt,name=msat_base_cost,json=msatBaseCost,proto3" json:"msat_base_cost,omitempty"`
	MsatPerUploadedByte  int64    `protobuf:"varint,2,opt,name=msat_per_uploaded_byte,json=msatPerUploadedByte,proto3" json:"msat_per_uploaded_byte,omitempty"`
	MsatPerDay           int64    `protobuf:"varint,3,opt,name=msat_per_day,json=msatPerDay,proto3" json:"msat_per_day,omitempty"`
	MsatPerDownloadByte  int64    `protobuf:"varint,4,opt,name=msat_per_download_byte,json=msatPerDownloadByte,proto3" json:"msat_per_download_byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeReport) Reset()         { *m = FeeReport{} }
func (m *FeeReport) String() string { return proto.CompactTextString(m) }
func (*FeeReport) ProtoMessage()    {}
func (*FeeReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *FeeReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeReport.Unmarshal(m, b)
}
func (m *FeeReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeReport.Marshal(b, m, deterministic)
}
func (m *FeeReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeReport.Merge(m, src)
}
func (m *FeeReport) XXX_Size() int {
	return xxx_messageInfo_FeeReport.Size(m)
}
func (m *FeeReport) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeReport.DiscardUnknown(m)
}

var xxx_messageInfo_FeeReport proto.InternalMessageInfo

func (m *FeeReport) GetMsatBaseCost() int64 {
	if m != nil {
		return m.MsatBaseCost
	}
	return 0
}

func (m *FeeReport) GetMsatPerUploadedByte() int64 {
	if m != nil {
		return m.MsatPerUploadedByte
	}
	return 0
}

func (m *FeeReport) GetMsatPerDay() int64 {
	if m != nil {
		return m.MsatPerDay
	}
	return 0
}

func (m *FeeReport) GetMsatPerDownloadByte() int64 {
	if m != nil {
		return m.MsatPerDownloadByte
	}
	return 0
}

type FileSlot struct {
	FileId               string   `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ShaChecksum          string   `protobuf:"bytes,4,opt,name=sha_checksum,json=shaChecksum,proto3" json:"sha_checksum,omitempty"`
	Bytes                int64    `protobuf:"varint,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
	CreationDate         int64    `protobuf:"varint,6,opt,name=creation_date,json=creationDate,proto3" json:"creation_date,omitempty"`
	DeletionDate         int64    `protobuf:"varint,7,opt,name=deletion_date,json=deletionDate,proto3" json:"deletion_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileSlot) Reset()         { *m = FileSlot{} }
func (m *FileSlot) String() string { return proto.CompactTextString(m) }
func (*FileSlot) ProtoMessage()    {}
func (*FileSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *FileSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSlot.Unmarshal(m, b)
}
func (m *FileSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSlot.Marshal(b, m, deterministic)
}
func (m *FileSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSlot.Merge(m, src)
}
func (m *FileSlot) XXX_Size() int {
	return xxx_messageInfo_FileSlot.Size(m)
}
func (m *FileSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSlot.DiscardUnknown(m)
}

var xxx_messageInfo_FileSlot proto.InternalMessageInfo

func (m *FileSlot) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func (m *FileSlot) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *FileSlot) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FileSlot) GetShaChecksum() string {
	if m != nil {
		return m.ShaChecksum
	}
	return ""
}

func (m *FileSlot) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *FileSlot) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *FileSlot) GetDeletionDate() int64 {
	if m != nil {
		return m.DeletionDate
	}
	return 0
}

type NewFileSlot struct {
	DeletionDate         int64    `protobuf:"varint,1,opt,name=deletion_date,json=deletionDate,proto3" json:"deletion_date,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewFileSlot) Reset()         { *m = NewFileSlot{} }
func (m *NewFileSlot) String() string { return proto.CompactTextString(m) }
func (*NewFileSlot) ProtoMessage()    {}
func (*NewFileSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *NewFileSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewFileSlot.Unmarshal(m, b)
}
func (m *NewFileSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewFileSlot.Marshal(b, m, deterministic)
}
func (m *NewFileSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewFileSlot.Merge(m, src)
}
func (m *NewFileSlot) XXX_Size() int {
	return xxx_messageInfo_NewFileSlot.Size(m)
}
func (m *NewFileSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_NewFileSlot.DiscardUnknown(m)
}

var xxx_messageInfo_NewFileSlot proto.InternalMessageInfo

func (m *NewFileSlot) GetDeletionDate() int64 {
	if m != nil {
		return m.DeletionDate
	}
	return 0
}

func (m *NewFileSlot) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *NewFileSlot) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type FileChunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type InvoiceResponse struct {
	Invoice              string   `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceResponse) Reset()         { *m = InvoiceResponse{} }
func (m *InvoiceResponse) String() string { return proto.CompactTextString(m) }
func (*InvoiceResponse) ProtoMessage()    {}
func (*InvoiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{12}
}

func (m *InvoiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceResponse.Unmarshal(m, b)
}
func (m *InvoiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceResponse.Marshal(b, m, deterministic)
}
func (m *InvoiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceResponse.Merge(m, src)
}
func (m *InvoiceResponse) XXX_Size() int {
	return xxx_messageInfo_InvoiceResponse.Size(m)
}
func (m *InvoiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceResponse proto.InternalMessageInfo

func (m *InvoiceResponse) GetInvoice() string {
	if m != nil {
		return m.Invoice
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{13}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetInfoRequest)(nil), "api.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "api.GetInfoResponse")
	proto.RegisterType((*ListFilesRequest)(nil), "api.ListFilesRequest")
	proto.RegisterType((*ListFilesResponse)(nil), "api.ListFilesResponse")
	proto.RegisterType((*UploadFileRequest)(nil), "api.UploadFileRequest")
	proto.RegisterType((*UploadFileResponse)(nil), "api.UploadFileResponse")
	proto.RegisterType((*DownloadFileRequest)(nil), "api.DownloadFileRequest")
	proto.RegisterType((*DownloadFileResponse)(nil), "api.DownloadFileResponse")
	proto.RegisterType((*FeeReport)(nil), "api.FeeReport")
	proto.RegisterType((*FileSlot)(nil), "api.FileSlot")
	proto.RegisterType((*NewFileSlot)(nil), "api.NewFileSlot")
	proto.RegisterType((*FileChunk)(nil), "api.FileChunk")
	proto.RegisterType((*InvoiceResponse)(nil), "api.InvoiceResponse")
	proto.RegisterType((*Empty)(nil), "api.Empty")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 682 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x8e, 0x9b, 0xa6, 0xa9, 0x27, 0x49, 0x9b, 0x6e, 0xf3, 0x6b, 0xfd, 0xcb, 0x29, 0xb8, 0x50,
	0x45, 0x42, 0x94, 0xaa, 0xe5, 0x80, 0x38, 0x41, 0xff, 0x91, 0x4a, 0x08, 0x55, 0x8b, 0x7a, 0xb6,
	0xb6, 0xf6, 0x44, 0x59, 0xd5, 0xf1, 0x1a, 0xef, 0xa6, 0x55, 0x1e, 0x80, 0x2b, 0x47, 0x5e, 0x80,
	0xe7, 0xe0, 0x6d, 0x78, 0x10, 0xb4, 0xbb, 0xb6, 0x9b, 0x3f, 0xe5, 0x02, 0xe2, 0x96, 0xfd, 0xe6,
	0x9b, 0x2f, 0xdf, 0xce, 0xce, 0x8c, 0xa1, 0xc5, 0x52, 0xfe, 0x92, 0xa5, 0xfc, 0x20, 0xcd, 0x84,
	0x12, 0xa4, 0xca, 0x52, 0xee, 0xb7, 0x61, 0xe3, 0x3d, 0xaa, 0xcb, 0x64, 0x28, 0x28, 0x7e, 0x9e,
	0xa0, 0x54, 0xfe, 0x5b, 0xd8, 0x2c, 0x11, 0x99, 0x8a, 0x44, 0x22, 0x79, 0x01, 0x30, 0x44, 0x0c,
	0x32, 0x4c, 0x45, 0xa6, 0x3c, 0xa7, 0xe7, 0xf4, 0x1b, 0x47, 0x1b, 0x07, 0x5a, 0xe9, 0x02, 0x91,
	0x1a, 0x94, 0xba, 0xc3, 0xe2, 0xa7, 0x4f, 0xa0, 0xfd, 0x81, 0x4b, 0x75, 0xc1, 0x63, 0x94, 0x85,
	0xea, 0x6b, 0xd8, 0x9a, 0xc1, 0x72, 0xdd, 0x3d, 0xa8, 0x0d, 0x35, 0xe0, 0x39, 0xbd, 0x6a, 0xbf,
	0x71, 0xd4, 0xb2, 0x92, 0x3c, 0xc6, 0x4f, 0xb1, 0x50, 0xd4, 0xc6, 0xfc, 0x6f, 0x0e, 0x6c, 0x5d,
	0xa7, 0xb1, 0x60, 0x91, 0x8e, 0xe4, 0x7a, 0x64, 0x1f, 0x56, 0x65, 0x2c, 0x0a, 0x33, 0x6d, 0x93,
	0xf9, 0x11, 0xef, 0x8b, 0xe4, 0x41, 0x85, 0x9a, 0x38, 0xd9, 0x87, 0x5a, 0x38, 0x9a, 0x24, 0xb7,
	0xde, 0xca, 0xac, 0x6b, 0x1e, 0xe3, 0xa9, 0x46, 0x07, 0x15, 0x6a, 0xc3, 0xa4, 0x0f, 0xeb, 0x43,
	0x9e, 0x70, 0x39, 0xc2, 0xc8, 0xab, 0x1a, 0x2a, 0x18, 0xea, 0xf9, 0x38, 0x55, 0xd3, 0x41, 0x85,
	0x96, 0xd1, 0x93, 0x3a, 0xd4, 0xf0, 0x0e, 0x13, 0xe5, 0x7f, 0x71, 0x80, 0xcc, 0x1a, 0xcb, 0x2f,
	0x75, 0x08, 0x75, 0x9e, 0xdc, 0x09, 0x1e, 0x62, 0x6e, 0xae, 0x63, 0x84, 0x2e, 0x2d, 0x56, 0xd0,
	0x06, 0x15, 0x5a, 0xd0, 0xc8, 0x2b, 0x68, 0x15, 0xea, 0x81, 0xbe, 0x73, 0xee, 0x75, 0xbe, 0x1c,
	0x83, 0x0a, 0x6d, 0x16, 0x2c, 0x8d, 0x3d, 0xf8, 0x38, 0x80, 0xed, 0x33, 0x71, 0x9f, 0x2c, 0x56,
	0x68, 0x17, 0xea, 0x5a, 0x2c, 0xe0, 0x91, 0xf1, 0xe1, 0xd2, 0x35, 0x7d, 0xbc, 0x8c, 0xfc, 0xef,
	0x0e, 0x74, 0xe6, 0x13, 0xfe, 0xd8, 0xf9, 0x3f, 0xac, 0xee, 0x0f, 0x07, 0xdc, 0xb2, 0xbb, 0xc8,
	0x53, 0xd8, 0x18, 0x4b, 0xa6, 0x82, 0x1b, 0x26, 0x31, 0x08, 0x85, 0xb4, 0x0f, 0x5f, 0xa5, 0x4d,
	0x8d, 0x9e, 0x30, 0x89, 0xa7, 0x42, 0x2a, 0x72, 0x0c, 0x3b, 0x86, 0x95, 0x62, 0x16, 0x4c, 0xcc,
	0xcb, 0x60, 0x14, 0xdc, 0x4c, 0x95, 0xad, 0x68, 0x95, 0x6e, 0xeb, 0xe8, 0x15, 0x66, 0xd7, 0x79,
	0xec, 0x64, 0xaa, 0x90, 0xf4, 0xa0, 0x59, 0x26, 0x45, 0x6c, 0x6a, 0xfc, 0x55, 0x29, 0xe4, 0xd4,
	0x33, 0x36, 0x9d, 0x93, 0x8d, 0xf2, 0xc2, 0x59, 0xd9, 0xd5, 0x39, 0xd9, 0xa2, 0xa8, 0x5a, 0xd6,
	0xff, 0xe9, 0xc0, 0x7a, 0xf1, 0x76, 0xbf, 0x7d, 0x0b, 0xd2, 0xd5, 0x85, 0x89, 0x31, 0x61, 0x63,
	0xeb, 0xd1, 0xa5, 0xe5, 0x99, 0xf4, 0xa0, 0x11, 0xa1, 0x0c, 0x33, 0x9e, 0x2a, 0x2e, 0x12, 0xe3,
	0xcb, 0xa5, 0xb3, 0x10, 0x79, 0x02, 0x4d, 0x39, 0x62, 0x41, 0x38, 0xc2, 0xf0, 0x56, 0x4e, 0xc6,
	0xc6, 0x8e, 0x4b, 0x1b, 0x72, 0xc4, 0x4e, 0x73, 0x88, 0x74, 0xa0, 0xa6, 0x9d, 0x4a, 0xaf, 0x66,
	0xac, 0xda, 0x03, 0xd9, 0x83, 0x56, 0x98, 0x21, 0xd3, 0x22, 0x41, 0xc4, 0x14, 0x7a, 0x6b, 0xb6,
	0x9a, 0x05, 0x78, 0xc6, 0x94, 0x9e, 0xce, 0x56, 0x84, 0x31, 0x3e, 0x90, 0xea, 0x96, 0x54, 0x80,
	0x9a, 0xe4, 0xa7, 0xd0, 0x98, 0x19, 0xbb, 0xe5, 0x1c, 0x67, 0x39, 0xe7, 0xef, 0x2e, 0xed, 0x3f,
	0x03, 0xb7, 0xec, 0x30, 0xe2, 0x41, 0x3d, 0x14, 0x89, 0xc2, 0xc4, 0x36, 0x44, 0x93, 0x16, 0x47,
	0xff, 0x39, 0x6c, 0x2e, 0x34, 0xae, 0x26, 0xcf, 0xf6, 0xb7, 0x5b, 0xf6, 0xb1, 0x5f, 0x87, 0x9a,
	0x69, 0xc5, 0xa3, 0xaf, 0x2b, 0xd0, 0xbe, 0xca, 0xf8, 0x1d, 0x53, 0x68, 0xee, 0xa4, 0x44, 0xa6,
	0xe7, 0xb3, 0x9e, 0x6f, 0x44, 0xb2, 0x6d, 0xda, 0x76, 0x7e, 0x63, 0x76, 0x3b, 0xf3, 0x60, 0xfe,
	0x6f, 0x6f, 0xc0, 0x2d, 0x37, 0x1e, 0xf9, 0xcf, 0x50, 0x16, 0xb7, 0x62, 0x77, 0x67, 0x11, 0xce,
	0x73, 0xdf, 0x01, 0x3c, 0x6c, 0x16, 0x62, 0x59, 0x4b, 0x3b, 0xb0, 0xbb, 0xbb, 0x84, 0xdb, 0xf4,
	0xbe, 0x73, 0xe8, 0x90, 0x73, 0x68, 0xce, 0x0e, 0x39, 0xf1, 0x0c, 0xf9, 0x91, 0x45, 0xd1, 0xfd,
	0xff, 0x91, 0x88, 0x15, 0x3a, 0x74, 0x6e, 0xd6, 0xcc, 0xb7, 0xe2, 0xf8, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x26, 0x24, 0x6c, 0x6a, 0x3c, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrivateFileStoreClient is the client API for PrivateFileStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrivateFileStoreClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (PrivateFileStore_UploadFileClient, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (PrivateFileStore_DownloadFileClient, error)
}

type privateFileStoreClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivateFileStoreClient(cc grpc.ClientConnInterface) PrivateFileStoreClient {
	return &privateFileStoreClient{cc}
}

func (c *privateFileStoreClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/api.PrivateFileStore/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateFileStoreClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, "/api.PrivateFileStore/ListFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privateFileStoreClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (PrivateFileStore_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrivateFileStore_serviceDesc.Streams[0], "/api.PrivateFileStore/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &privateFileStoreUploadFileClient{stream}
	return x, nil
}

type PrivateFileStore_UploadFileClient interface {
	Send(*UploadFileRequest) error
	Recv() (*UploadFileResponse, error)
	grpc.ClientStream
}

type privateFileStoreUploadFileClient struct {
	grpc.ClientStream
}

func (x *privateFileStoreUploadFileClient) Send(m *UploadFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *privateFileStoreUploadFileClient) Recv() (*UploadFileResponse, error) {
	m := new(UploadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *privateFileStoreClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (PrivateFileStore_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PrivateFileStore_serviceDesc.Streams[1], "/api.PrivateFileStore/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &privateFileStoreDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PrivateFileStore_DownloadFileClient interface {
	Recv() (*DownloadFileResponse, error)
	grpc.ClientStream
}

type privateFileStoreDownloadFileClient struct {
	grpc.ClientStream
}

func (x *privateFileStoreDownloadFileClient) Recv() (*DownloadFileResponse, error) {
	m := new(DownloadFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PrivateFileStoreServer is the server API for PrivateFileStore service.
type PrivateFileStoreServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	UploadFile(PrivateFileStore_UploadFileServer) error
	DownloadFile(*DownloadFileRequest, PrivateFileStore_DownloadFileServer) error
}

// UnimplementedPrivateFileStoreServer can be embedded to have forward compatible implementations.
type UnimplementedPrivateFileStoreServer struct {
}

func (*UnimplementedPrivateFileStoreServer) GetInfo(ctx context.Context, req *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedPrivateFileStoreServer) ListFiles(ctx context.Context, req *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFiles not implemented")
}
func (*UnimplementedPrivateFileStoreServer) UploadFile(srv PrivateFileStore_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (*UnimplementedPrivateFileStoreServer) DownloadFile(req *DownloadFileRequest, srv PrivateFileStore_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}

func RegisterPrivateFileStoreServer(s *grpc.Server, srv PrivateFileStoreServer) {
	s.RegisterService(&_PrivateFileStore_serviceDesc, srv)
}

func _PrivateFileStore_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateFileStoreServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrivateFileStore/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateFileStoreServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateFileStore_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivateFileStoreServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrivateFileStore/ListFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivateFileStoreServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivateFileStore_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PrivateFileStoreServer).UploadFile(&privateFileStoreUploadFileServer{stream})
}

type PrivateFileStore_UploadFileServer interface {
	Send(*UploadFileResponse) error
	Recv() (*UploadFileRequest, error)
	grpc.ServerStream
}

type privateFileStoreUploadFileServer struct {
	grpc.ServerStream
}

func (x *privateFileStoreUploadFileServer) Send(m *UploadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *privateFileStoreUploadFileServer) Recv() (*UploadFileRequest, error) {
	m := new(UploadFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PrivateFileStore_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PrivateFileStoreServer).DownloadFile(m, &privateFileStoreDownloadFileServer{stream})
}

type PrivateFileStore_DownloadFileServer interface {
	Send(*DownloadFileResponse) error
	grpc.ServerStream
}

type privateFileStoreDownloadFileServer struct {
	grpc.ServerStream
}

func (x *privateFileStoreDownloadFileServer) Send(m *DownloadFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PrivateFileStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PrivateFileStore",
	HandlerType: (*PrivateFileStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PrivateFileStore_GetInfo_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _PrivateFileStore_ListFiles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _PrivateFileStore_UploadFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _PrivateFileStore_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
